---
title: "Predictions with Stan models"
author: "David Prieto-Merino"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    df_print: paged
    self.contained: true
  word_document:
    toc: true
  pdf_document:
    toc: true
highlight: tango
includes:
  toc_depth: 4
editor_options:
  chunk_output_type: console
---

```{=html}
<style>
body {
  text-align: justify}
</style>
```

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo=FALSE)
options(scipen = 999) #quitar notación científica

library(MASS)
library(readxl)
library(tidyverse)
library(flextable)
library(rmdformats)
library(confintr)
library(MCMCvis)
library(bayesplot)
library(rstudioapi)
library(callr)
library(Hmisc)
library(ggpubr)
library(sp)
library(rstatix)
library(haven)
require(rstan)



source("Bayesian_COD_Stan_functions_2025.R") # load functions

```



```{r functions}

#point_HM("Stan_HM_CD", "new", "unc", "2025")
PFXM<- "Stan_HM_CD"
PFX<- "Stan_LM"
ESD<- "new"
DEA<- "unc"
YPR<- "2025"
SDR<- 0.07
LAM<- 150
NP<- 2

#  Point-Estimate predictions with High Mortality models
# 
point_HM <- function(PFX, ESD, DEA, YPR, SDR=0.07, LAM=150, NP=2){
  # PFX <- Prefix fo model e.g. "Stan_HM_CD"
  # ESD <- estimation data ("old" / "new")
  # DEA <- "unc" / "cal" for calibration of deaths
  # YPR <- "2025" prediction data ("2020" / "2025")
  # SDR <- 0.07
  # LAM <- 150
  # NP: Number of samples (at least 2..!!!!!! otherwise, problems in the function f.par)
  # 
  MOD <- paste(PFX,ESD,DEA,SDR,LAM,sep="_")
  
  # Put the appropriate model to load
  load(paste0("MODELS/",MOD,".RData"))
  
  # Get parameter samples from the Stan model (use same samples in all predictions)
  PS <- f.par(get(MOD), NP=NP)
  
  # Predictions for all countries
  # EARLY deaths
  PHM_early <- f.pr2(PS, paste0("data.predict_all_",YPR), PE="early")
  # LATE deaths
  PHM_late <- f.pr2(PS, paste0("data.predict_all_",YPR), PE="late")
summary(PHM_late$Point_estimates)

  # Combine indian states and put together early and late
  # JP 9/22/25 - leave indian states until very end
head(PHM_late$Point_estimates)
  dim(PHM_late$Point_estimates)
  table(table(PHM_late$Point_estimates$iso3, PHM_late$Point_estimates$year))
  table(table(PHM_late$Point_estimates$year))
  unique(PHM_late$Point_estimates$iso3)  
  unique(PHM_late$Point_estimates$country)  
  
  PHM <- PHM_late$Point_estimates %>%
 #  left_join(transmute(PHM_late$Prediction.Data, iso3, year, nnd)) %>%
 #  mutate(iso3=ifelse(nchar(iso3)==4, "IND",iso3)) %>%
   group_by(iso3, year, cod) %>% 
    summarise(mf=mean(pf.me), 
              mr=mean(pr.me),
              qf=mean(pf.q2), 
              qr=mean(pr.q2)) %>%
    pivot_longer(cols=mf:qr, names_to="model", values_to="HMl")
    summary(PHM)
    
    names(PHM)
  PHM <- PHM_early$Point_estimates %>%
    group_by(iso3, year, cod) %>% 
    summarise(mf=mean(pf.me), 
              mr=mean(pr.me),
              qf=mean(pf.q2), 
              qr=mean(pr.q2)) %>%
    pivot_longer(cols=mf:qr, names_to="model", values_to="HMe") %>%
    full_join(PHM) %>%
    mutate(HM=0.74*HMe+0.26*HMl, est=ESD, pre=YPR, HM_cal=DEA, HM_sdr=SDR, HM_lam=LAM) 
  
  return(PHM)
}


# For prediction with Low Mortality models
# 
point_LM <- function(PFX, ESD, YPR, SDR=0.07, LAM=1, NP=2){
  # PFX <- Prefix fo model e.g. "Stan_HM_CD"
  # ESD <- estimation data ("old" / "new")
  # YPR <- "2025" prediction data ("2020" / "2025")
  # SDR <- 0.07
  # LAM <- 1
  # NP: Number of samples (at least 2..!!!!!! otherwise, problems in the function f.par)
  #
    
  # Early model
  MODe <- paste(PFX,"early",ESD,SDR,LAM,sep="_")
  #list.files("../results/")
  load(paste0("MODELS/",MODe,".RData"))
  # Get parameter samples from the Stan model (use same samples in all predictions)
  PSe <- f.par(get(MODe), NP=NP)
  # Predictions for all countries
  PLM_early <- f.pr2(PSe, paste0("data.predict_all_",YPR))
    
  # Late model
  MODl <- paste(PFX,"late",ESD,SDR,LAM,sep="_")
  load(paste0("MODELS/",MODl,".RData"))
  # Get parameter samples from the Stan model (use same samples in all predictions)
  PSl <- f.par(get(MODl), NP=10)
  # Predictions for all countries
  PLM_late <- f.pr2(PSl, paste0("data.predict_all_",YPR)) 
  
  # Combine indian states and put together early and late

  PLM <- PLM_late$Point_estimates %>%
    group_by(iso3, year, cod) %>%
    summarise(mf=mean(pf.me), 
              mr=mean(pr.me),
              qf=mean(pf.q2), 
              qr=mean(pr.q2))%>%
    pivot_longer(cols=mf:qr, names_to="model", values_to="LMl")
  summary(PLM)  
  PLM <- PLM_early$Point_estimates %>%
    group_by(iso3, year, cod) %>%
    summarise(mf=mean(pf.me), 
              mr=mean(pr.me),
              qf=mean(pf.q2), 
              qr=mean(pr.q2)) %>%
    pivot_longer(cols=mf:qr, names_to="model", values_to="LMe")%>%
    full_join(PLM) %>%
    mutate(LM=0.74*LMe+0.26*LMl, est=ESD, pre=YPR, LM_sdr=SDR, LM_lam=LAM)
    
  return(PLM)
}


```




```{r load_prediction_data}

# Table of ountries (WHO)
countries <-  read_xlsx("DATA/CountryModelClass_20240814.xlsx")

# Countries with VR data for models
vrcountries <- read_dta("DATA/good_VRneonates_observed_20250828.dta")

# Discrepancies between both datasets of VR countries
vr1 <- countries$ISO3[grepl("VR",countries$Group)]
vr2 <- unique(vrcountries$isocode)



## New Prediciton data from countries
##
pred_wide_2025 <- read_csv("DATA/CovariateDatabase2023-wide_20250728.csv")
data.predict_2025 <- transmute(pred_wide_2025, iso3, country=country_name, year,
                               intercept = 1,
                               u5mr=u5mr_sm, nmr=nmr_sm,
                               gfr=ifelse(gfr_sm<0.001, gfr_sm*1000, gfr_sm),
                               sba=ifelse(sab_sm<=1, sab_sm*100, sab_sm), 
                               lbw=lbw_sm*100, dpt=vac_dtp3_sm*100, bcg=vac_bcg_sm*100,
                               pab=pab_sm*100, femlit=literacy_f_sm*100,
                               gni=gni_sm, gini=gini_sm, anc=anc4_sm) %>%
  filter(year>=2000) %>%
  mutate(pid=c(1:nrow(.))) 



##############################################.
## New Data from Indian States

pred_ind_2025 <- read_csv("DATA/CovariateDatabaseIndia2023-wide_20250724.csv")
# prepare dataset for india
data.predict_ind_2025 <- transmute(pred_ind_2025, iso3=india_state, country=region_name, year,
                               intercept = 1,
                               nnd = round(nnd_sm),
                               u5mr=100*u5mr_sm, nmr=100*nmr_sm,
                               sba=ifelse(sab_sm<=1, sab_sm*100, sab_sm), 
                               lbw=lbw_sm*100, dpt=vac_dtp3_sm*100, bcg=vac_bcg_sm*100,
                               femlit=literacy_f_sm*100, anc=anc4_sm,
                               gfr=ifelse(gfr_sm<0.001, gfr_sm*1000, gfr_sm),
                               pab=pab_sm*100) %>%
  # add gini from national level
  left_join(transmute(filter(data.predict_2025, iso3=="IND"), year, gini, gni)) %>%
  filter(year>=2000) %>% arrange(iso3, year) %>% mutate(pid=c(1:nrow(.))) %>%
  group_by(iso3) %>% mutate(lbw=ifelse(is.na(lbw),lag(lbw),lbw), nnd=ifelse(is.na(nnd),lag(nnd),nnd)) %>% ungroup()
#table(data.predict_ind_2025$iso3)
summary(data.predict_ind_2025$dpt)
tapply(data.predict_ind_2025$dpt, data.predict_ind_2025$year, summary)
tapply(data.predict_ind_2025$pab, data.predict_ind_2025$year, summary)

data.predict_all_2025 <- filter(data.predict_2025, iso3!="IND") %>% 
                         mutate(nnd=1) %>% 
                         bind_rows(data.predict_ind_2025, .id="data")
table(data.predict_all_2025$year)
summary(data.predict_all_2025)
table(data.predict_all_2025$iso3)

d24<- data.predict_all_2025 %>% filter(year==2023)
d24$year<- 2024
data.predict_all_2025<- rbind(data.predict_all_2025, d24)

```





## Prediction with HIGH mortality models

```{r}
# load Stan model and apply predictions
PHM <- bind_rows(point_HM("Stan_HM_CD", "new", "unc", "2025"),
                 point_HM("Stan_HM_CD", "new", "cal", "2025"))
```



## Prediction with LOW mortality models

```{r}
# load Stan model and apply predictions
PLM <- bind_rows(point_LM("Stan_LM", "new", "2025"))
```



## Put all predictions in one large table:

```{r}

PHM <- left_join(PHM, data.predict_all_2025[,c("iso3","year","nmr")], by=c("iso3","year"))


PHLM <- transmute(PHM, model, pre, HM_cal, iso3, year, nmr, cod, HM) %>%
  pivot_wider(names_from=cod, values_from=HM) %>%
  mutate(injuries=0) %>% 
  pivot_longer(cols=-all_of(c("model", "pre", "HM_cal", "iso3", "year", "nmr")), names_to="cod", values_to="HM") %>%
  left_join(
    transmute(PLM, model, pre, iso3, year, cod, LM) %>%
    pivot_wider(names_from=cod, values_from=LM) %>%
    mutate(diarrhoea=0, tetanus=0)%>%
    pivot_longer(cols=-all_of(c("model", "pre", "iso3", "year")), names_to="cod", values_to="LM")) %>%
  mutate(whm=min(1,max((nmr-10)/10,0)),
         AM = (whm*HM + (1-whm)*LM))


```



## Save predictions in long and wide format


```{r}

save(PHLM, file="PREDICTIONS/PointEstimates_neonates_long.RData")

PHLw <- filter(PHLM, model=="qr") %>% 
  mutate(HM=NULL, LM=NULL) %>% 
  pivot_wider(names_from=cod, values_from=AM) 

causes<- c("congenital","diarrhoea","intrapartum","other","pneumonia",
           "preterm","sepsis","tetanus","injuries")

for(cs in causes) PHLw[, paste0("f_",cs)]<- PHLw[, cs]

save(PHLw, file="PREDICTIONS/PointEstimates_neonates_wide.RData")
write.csv(PHLw, file="PREDICTIONS/PointEstimates_neonates_wide.csv")

```



```{r}

mutate(PHLM, HM=NULL, LM=NULL) %>% pivot_wider(names_from=model, values_from=AM) %>%
ggplot(aes(x=mr, y=qr, col=iso3)) + geom_point() + facet_grid(rows=vars(cod), cols=vars(pre)) + theme(legend.position="none") + geom_abline(intercept=0, slope=1)

mutate(PHLM, HM=NULL, LM=NULL) %>% pivot_wider(names_from=model, values_from=AM) %>%
ggplot(aes(x=qf, y=qr, col=iso3)) + geom_point() + facet_grid(rows=vars(cod), cols=vars(pre)) + theme(legend.position="none") + geom_abline(intercept=0, slope=1)

```





